package com.mp_tests.projectdummy;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ObjectDummy implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer input_numeric;
	private java.lang.String input_string;
	private java.lang.Boolean output_boolean;
	private java.lang.String output_string;

	public ObjectDummy() {
	}

	public java.lang.Integer getInput_numeric() {
		return this.input_numeric;
	}

	public void setInput_numeric(java.lang.Integer input_numeric) {
		this.input_numeric = input_numeric;
	}

	public java.lang.String getInput_string() {
		return this.input_string;
	}

	public void setInput_string(java.lang.String input_string) {
		this.input_string = input_string;
	}

	public java.lang.Boolean getOutput_boolean() {
		return this.output_boolean;
	}

	public void setOutput_boolean(java.lang.Boolean output_boolean) {
		this.output_boolean = output_boolean;
	}

	public java.lang.String getOutput_string() {
		return this.output_string;
	}

	public void setOutput_string(java.lang.String output_string) {
		this.output_string = output_string;
	}

	public ObjectDummy(java.lang.Integer input_numeric,
			java.lang.String input_string, java.lang.Boolean output_boolean,
			java.lang.String output_string) {
		this.input_numeric = input_numeric;
		this.input_string = input_string;
		this.output_boolean = output_boolean;
		this.output_string = output_string;
	}

}